import { lazy } from "react";
import {
  Braces,
  Code2,
  FileCode2,
  Regex,
  Binary,
  KeyRound,
  Hash,
  Fingerprint,
  FileText,
  Paintbrush,
  QrCode,
  ShieldCheck,
  Clock,
  GitCompare,
  Clipboard,
  Wrench,
  Palette,
  Shapes,
  Type,
  Sparkles,
  ImageIcon,
  Network,
  FileStack,
  StickyNote,
  History,
  Link2,
  Rows3,
  LayoutList,
  Table,
  PenSquare,
  Terminal,
  DatabaseZap,
  KanbanSquare,
  FolderTree,
  Workflow,
  BookOpen,
  Boxes,
  type LucideIcon,
} from "lucide-react";
import type { ToolCategory, ToolDefinition } from "../types/tool";

export const categories: ToolCategory[] = [
  { id: "code", label: "Code", icon: Code2 },
  { id: "design", label: "Design", icon: Palette },
  { id: "database", label: "Database", icon: DatabaseZap },
  { id: "api", label: "API", icon: Network },
  { id: "project", label: "Project", icon: Boxes },
  { id: "documents", label: "Documents", icon: FileStack },
  { id: "utilities", label: "Utilities", icon: Wrench },
  { id: "workspace-tools", label: "Workspace", icon: StickyNote },
];

export const tools: ToolDefinition[] = [
  {
    id: "json",
    title: "JSON",
    description: "Format & validate",
    category: "code",
    icon: Braces,
    component: lazy(() => import("./code-tools/JsonTool")),
    keywords: ["json", "format", "validate"],
  },
  {
    id: "html",
    title: "HTML",
    description: "Beautify & minify",
    category: "code",
    icon: FileCode2,
    component: lazy(() => import("./code-tools/HtmlTool")),
    keywords: ["html", "markup"],
  },
  {
    id: "css",
    title: "CSS",
    description: "Beautify & minify",
    category: "code",
    icon: Paintbrush,
    component: lazy(() => import("./code-tools/CssTool")),
    keywords: ["css", "styles"],
  },
  {
    id: "js",
    title: "JavaScript",
    description: "Beautify & minify",
    category: "code",
    icon: FileCode2,
    component: lazy(() => import("./code-tools/JsTool")),
    keywords: ["javascript", "js"],
  },
  {
    id: "ts",
    title: "TypeScript",
    description: "Beautify & minify",
    category: "code",
    icon: FileCode2,
    component: lazy(() => import("./code-tools/TsTool")),
    keywords: ["typescript", "ts"],
  },
  {
    id: "markdown",
    title: "Markdown",
    description: "Live preview",
    category: "code",
    icon: FileText,
    component: lazy(() => import("./code-tools/MarkdownTool")),
    keywords: ["markdown", "md", "preview"],
  },
  {
    id: "regex",
    title: "Regex Tester",
    description: "Match & highlight",
    category: "code",
    icon: Regex,
    component: lazy(() => import("./code-tools/RegexTool")),
    keywords: ["regex", "regexp", "pattern"],
  },
  {
    id: "base64",
    title: "Base64",
    description: "Encode & decode",
    category: "code",
    icon: Binary,
    component: lazy(() => import("./code-tools/Base64Tool")),
    keywords: ["base64", "encode", "decode"],
  },
  {
    id: "jwt",
    title: "JWT Decoder",
    description: "Inspect claims",
    category: "code",
    icon: KeyRound,
    component: lazy(() => import("./code-tools/JwtTool")),
    keywords: ["jwt", "token", "auth"],
  },
  {
    id: "hash",
    title: "Hash Generator",
    description: "SHA-1 / 256 / 384 / 512",
    category: "code",
    icon: Hash,
    component: lazy(() => import("./code-tools/HashTool")),
    keywords: ["hash", "sha", "checksum"],
  },
  {
    id: "uuid",
    title: "UUID Generator",
    description: "RFC 4122 v4",
    category: "code",
    icon: Fingerprint,
    component: lazy(() => import("./code-tools/UuidTool")),
    keywords: ["uuid", "guid", "id"],
  },
  {
    id: "colors",
    title: "Color Tool",
    description: "Convert, shades, contrast",
    category: "design",
    icon: Palette,
    component: lazy(() => import("./design/ColorTool")),
    keywords: ["color", "hex", "rgb", "hsl", "palette", "contrast"],
  },
  {
    id: "svg",
    title: "SVG Preview",
    description: "Preview & minify",
    category: "design",
    icon: Shapes,
    component: lazy(() => import("./design/SvgTool")),
    keywords: ["svg", "vector", "icon"],
  },
  {
    id: "fonts",
    title: "Font Pairing",
    description: "Preview Google Fonts",
    category: "design",
    icon: Type,
    component: lazy(() => import("./design/FontTool")),
    keywords: ["fonts", "typography", "pairing"],
  },
  {
    id: "icons",
    title: "Icon Browser",
    description: "Search & copy Lucide icons",
    category: "design",
    icon: Sparkles,
    component: lazy(() => import("./design/IconTool")),
    keywords: ["icons", "lucide", "svg"],
  },
  {
    id: "image",
    title: "Image Utilities",
    description: "Resize, convert, compress",
    category: "design",
    icon: ImageIcon,
    component: lazy(() => import("./design/ImageTool")),
    keywords: ["image", "resize", "compress", "convert"],
  },
  {
    id: "qr",
    title: "QR Code",
    description: "Generate & download",
    category: "utilities",
    icon: QrCode,
    component: lazy(() => import("./utilities/QrTool")),
    keywords: ["qr", "code", "barcode"],
  },
  {
    id: "password",
    title: "Password Generator",
    description: "Strong & random",
    category: "utilities",
    icon: ShieldCheck,
    component: lazy(() => import("./utilities/PasswordTool")),
    keywords: ["password", "secure", "generator"],
  },
  {
    id: "timestamp",
    title: "Timestamp",
    description: "Unix ⇄ human date",
    category: "utilities",
    icon: Clock,
    component: lazy(() => import("./utilities/TimestampTool")),
    keywords: ["timestamp", "unix", "epoch", "date"],
  },
  {
    id: "diff",
    title: "Diff Checker",
    description: "Compare two texts",
    category: "utilities",
    icon: GitCompare,
    component: lazy(() => import("./utilities/DiffTool")),
    keywords: ["diff", "compare", "text"],
  },
  {
    id: "clipboard",
    title: "Clipboard Board",
    description: "Multi-slot snippets",
    category: "utilities",
    icon: Clipboard,
    component: lazy(() => import("./utilities/ClipboardTool")),
    keywords: ["clipboard", "snippets", "paste"],
  },
  {
    id: "url",
    title: "URL Tools",
    description: "Parse & encode/decode",
    category: "api",
    icon: Link2,
    component: lazy(() => import("./api/UrlTool")),
    keywords: ["url", "parse", "encode", "decode"],
  },
  {
    id: "headers",
    title: "Header Builder",
    description: "curl, fetch, raw",
    category: "api",
    icon: Rows3,
    component: lazy(() => import("./api/HeaderTool")),
    keywords: ["headers", "http", "curl", "fetch"],
  },
  {
    id: "api-designer",
    title: "API Designer",
    description: "Sketch endpoints",
    category: "api",
    icon: LayoutList,
    component: lazy(() => import("./api/ApiDesignerTool")),
    keywords: ["api", "endpoints", "rest", "design"],
  },
  {
    id: "csv",
    title: "CSV Viewer",
    description: "View & convert to JSON",
    category: "documents",
    icon: Table,
    component: lazy(() => import("./documents/CsvTool")),
    keywords: ["csv", "table", "json"],
  },
  {
    id: "text-studio",
    title: "Text Studio",
    description: "Case, counting, replace",
    category: "documents",
    icon: PenSquare,
    component: lazy(() => import("./documents/TextStudioTool")),
    keywords: ["text", "case", "count", "replace"],
  },
  {
    id: "pdf",
    title: "PDF Merge",
    description: "Combine PDFs locally",
    category: "documents",
    icon: FileStack,
    component: lazy(() => import("./documents/PdfTool")),
    keywords: ["pdf", "merge", "combine"],
  },
  {
    id: "notes",
    title: "Notes",
    description: "Quick local notes",
    category: "workspace-tools",
    icon: StickyNote,
    component: lazy(() => import("./workspace-tools/NotesTool")),
    keywords: ["notes", "write"],
  },
  {
    id: "snippets",
    title: "Snippets",
    description: "Reusable code library",
    category: "workspace-tools",
    icon: Terminal,
    component: lazy(() => import("./workspace-tools/SnippetsTool")),
    keywords: ["snippets", "code", "library"],
  },
  {
    id: "history",
    title: "History",
    description: "Recently opened tools",
    category: "workspace-tools",
    icon: History,
    component: lazy(() => import("./workspace-tools/HistoryTool")),
    keywords: ["history", "recent", "log"],
  },
  {
    id: "er-designer",
    title: "ER Designer",
    description: "Visual schema diagrams",
    category: "database",
    icon: DatabaseZap,
    component: lazy(() => import("./database/ErDesignerTool")),
    keywords: ["er", "schema", "database", "diagram", "tables"],
  },
  {
    id: "sql-builder",
    title: "SQL Builder",
    description: "Visual query builder",
    category: "database",
    icon: Terminal,
    component: lazy(() => import("./database/SqlBuilderTool")),
    keywords: ["sql", "query", "builder", "select"],
  },
  {
    id: "sqlite",
    title: "SQLite Viewer",
    description: "Run SQL in-browser",
    category: "database",
    icon: DatabaseZap,
    component: lazy(() => import("./database/SqliteTool")),
    keywords: ["sqlite", "database", "sql", "query"],
  },
  {
    id: "data-generator",
    title: "Data Generator",
    description: "Mock data, JSON/CSV",
    category: "database",
    icon: Table,
    component: lazy(() => import("./database/DataGeneratorTool")),
    keywords: ["mock", "fake", "data", "generator", "seed"],
  },
  {
    id: "project-planner",
    title: "Project Planner",
    description: "Kanban board",
    category: "project",
    icon: KanbanSquare,
    component: lazy(() => import("./project/ProjectPlannerTool")),
    keywords: ["kanban", "tasks", "planner", "board"],
  },
  {
    id: "folder-generator",
    title: "Folder Generator",
    description: "Tree to ZIP scaffold",
    category: "project",
    icon: FolderTree,
    component: lazy(() => import("./project/FolderGeneratorTool")),
    keywords: ["folder", "scaffold", "zip", "structure"],
  },
  {
    id: "architecture",
    title: "Architecture",
    description: "System diagrams",
    category: "project",
    icon: Boxes,
    component: lazy(() => import("./project/ArchitectureTool")),
    keywords: ["architecture", "system", "diagram", "components"],
  },
  {
    id: "documentation",
    title: "Documentation",
    description: "Multi-page docs",
    category: "project",
    icon: BookOpen,
    component: lazy(() => import("./project/DocumentationTool")),
    keywords: ["docs", "documentation", "markdown", "wiki"],
  },
  {
    id: "flowcharts",
    title: "Flowcharts",
    description: "Process flow diagrams",
    category: "project",
    icon: Workflow,
    component: lazy(() => import("./project/FlowchartTool")),
    keywords: ["flowchart", "process", "diagram"],
  },
];

export function getTool(id: string) {
  return tools.find((t) => t.id === id);
}

export function iconFor(id: string): LucideIcon {
  return getTool(id)?.icon ?? Code2;
}
